@host = http://localhost:5084

### Получить все счётчики
GET {{host}}/meters
Accept: application/json

###

### Получить счётчик по id
GET {{host}}/meters/1
Accept: application/json

###

### Создать счётчик
POST {{host}}/meters
Content-Type: application/json

{
    "premiseId": 1,
    "meterType": 0,
    "tariff": null
}

###

### Обновить активность счётчика
PUT {{host}}/meters/1
Content-Type: application/json

{
    "isActive": false
}

### Получить помещения (с фильтрацией по роли)
GET {{host}}/premises
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoi0JjQstCw0L0g0JLQsNGB0LjQu9GM0LXQstC40YciLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJBZG1pbiIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL25hbWVpZGVudGlmaWVyIjoiMSIsImV4cCI6MTc4MzU0MzIyNCwiaXNzIjoiTWV0ZXJUcmFja2VyQXBpIiwiYXVkIjoiTWV0ZXJUcmFja2VyQXBpVXNlcnMifQ.DgbAofhlh4GxsUvRMdLlZif1-CyAnhjHZcMVLbPRkxk
Accept: application/json


###

### Получить помещение по id
GET {{host}}/premises/1
Accept: application/json

###

### Создать помещение
POST {{host}}/premises
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoi0JjQstCw0L0g0JLQsNGB0LjQu9GM0LXQstC40YciLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJBZG1pbiIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL25hbWVpZGVudGlmaWVyIjoiMSIsImV4cCI6MTc4MzU0MzM2OSwiaXNzIjoiTWV0ZXJUcmFja2VyQXBpIiwiYXVkIjoiTWV0ZXJUcmFja2VyQXBpVXNlcnMifQ.aHVR9czvvsox_109xLeRQzGWWuUyMgQgfH_-ojVsw5Q

{
    "address": "ул. Ленина, 10, офис 5",
    "responsibleUserId": 1
}

###

### Обновить ответственного (подмена)
PUT {{host}}/premises/1
Content-Type: application/json

{
    "responsibleUserId": 2
}

###

### Получить все показания
GET {{host}}/readings
Accept: application/json

###

### Получить показание по id
GET {{host}}/readings/1
Accept: application/json

###

### Создать показание
POST {{host}}/readings
Content-Type: application/json

{
    "meterId": 1,
    "value": "7737",
    "photoUrl": "ссылка на юрл"
}

###

### Обновить показание
PUT {{host}}/readings/1
Content-Type: application/json

{
    "value": "7777",
    "photoUrl": "ссылка на юрл"
}

###

POST {{host}}/auth/login
Content-Type: application/json

{
    "name": "Иван",
    "password": "4505"
}