CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;
CREATE TABLE "Users" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NOT NULL,
    "Role" integer NOT NULL,
    "Password" text NOT NULL,
    CONSTRAINT "PK_Users" PRIMARY KEY ("Id")
);

CREATE TABLE "Premises" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Address" text NOT NULL,
    "ResponsibleUserId" integer NOT NULL,
    CONSTRAINT "PK_Premises" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Premises_Users_ResponsibleUserId" FOREIGN KEY ("ResponsibleUserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Meters" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "PremiseId" integer NOT NULL,
    "MeterType" integer NOT NULL,
    "Tariff" integer,
    "IsActive" boolean NOT NULL,
    CONSTRAINT "PK_Meters" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Meters_Premises_PremiseId" FOREIGN KEY ("PremiseId") REFERENCES "Premises" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Readings" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "MeterId" integer NOT NULL,
    "Value" numeric NOT NULL,
    "ReadingDate" timestamp with time zone NOT NULL,
    "SubmittedById" integer NOT NULL,
    "PhotoUrl" text,
    CONSTRAINT "PK_Readings" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Readings_Meters_MeterId" FOREIGN KEY ("MeterId") REFERENCES "Meters" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Readings_Users_SubmittedById" FOREIGN KEY ("SubmittedById") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_Meters_PremiseId" ON "Meters" ("PremiseId");

CREATE INDEX "IX_Premises_ResponsibleUserId" ON "Premises" ("ResponsibleUserId");

CREATE INDEX "IX_Readings_MeterId" ON "Readings" ("MeterId");

CREATE INDEX "IX_Readings_SubmittedById" ON "Readings" ("SubmittedById");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260712213215_InitialCreate', '10.0.9');

COMMIT;

START TRANSACTION;
ALTER TABLE "Premises" DROP CONSTRAINT "FK_Premises_Users_ResponsibleUserId";

ALTER TABLE "Readings" DROP CONSTRAINT "FK_Readings_Users_SubmittedById";

ALTER TABLE "Premises" ALTER COLUMN "ResponsibleUserId" DROP NOT NULL;

ALTER TABLE "Premises" ADD CONSTRAINT "FK_Premises_Users_ResponsibleUserId" FOREIGN KEY ("ResponsibleUserId") REFERENCES "Users" ("Id") ON DELETE SET NULL;

ALTER TABLE "Readings" ADD CONSTRAINT "FK_Readings_Users_SubmittedById" FOREIGN KEY ("SubmittedById") REFERENCES "Users" ("Id") ON DELETE RESTRICT;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260714141948_UpdateDeleteBehaviors', '10.0.9');

COMMIT;

START TRANSACTION;
ALTER TABLE "Premises" ADD "TenantName" text;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260717144950_AddTenantToPremise', '10.0.9');

COMMIT;

